[build]
    base = "new-club-website"     # 👈 tells Netlify your app lives here
    command = "npm run build"
    publish = "new-club-website/dist"

[build.environment]
    NODE_VERSION = "20"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200